# Generated by Django 4.0.3 on 2022-04-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_cat',
            field=models.CharField(max_length=50, verbose_name='Category'),
        ),
    ]
